codecov:
  branch: master
  ci:
    - drone.nextcloud.com

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.5

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
  require_changes: false

ignore:
  - "src/main/res/values*/*"

